Weather app
tirthajyoti-ghosh/weather-app pull request #1
Opened 2020-07-25 06:21 UTC by tirthajyoti-ghosh

# Weather App

This is a weather app that shows temperatures (current, feels like, min, max), cloudiness (%), and wind speed (m/s) by city name. The city name is obtained from form input. This app consumes OpenWeather API in the `JSON` format to show weather data.

Data points consumed:

* City name
* Country code
* Weather description
* Weather icon
* Current temperature
* Feels like temperature
* Minimum temperature
* Maximum temperature
* Cloudiness
* Wind speed

## Usage

![Usage example](https://user-images.githubusercontent.com/57726348/88450206-d98d6900-ce6a-11ea-9256-f20becd92fe2.jpg)

1. Enter the city name and press the `Enter` key.
2. Weather data is displayed here.
3. These are buttons to convert the temperature in their respective units.

2020-07-26 11:07 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

* [x] Your app's appearance should change based on the received data. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))

* [x] Keep the application logic separated from DOM manipulation tasks ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png) from Pathwright)

**KIndly submit another CRR once these issues have been solved.** _Happy coding!_ 🎉

2020-07-26 11:07 UTC, suretrust commented on src/main.js
> +    wind: response.wind.speed,
* [ ] ES6 - use object destructuring to get the values from an object. This way you can avoid repeating a lot of code. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/destructuring_requirement.png) from Pathwright)
```javascript
const { name, sys, weather, main, clouds, wind } = response
```

2020-07-26 12:17 UTC, tirthajyoti-ghosh commented
Thanks to @suretrust for the review.

Changes made after review:

- Add destructuring 
  - Separate DOM from logic
  - Remove wet code

Regarding this - 
>Your app's appearance should change based on the received data.

The weather image on the right side changes based on the weather. 

![image](https://user-images.githubusercontent.com/57726348/88478608-73d2d700-cf67-11ea-9a30-4f024f1cfe61.png)

![image](https://user-images.githubusercontent.com/57726348/88478613-7df4d580-cf67-11ea-8f8c-11f4cdfad9ce.png)

![image](https://user-images.githubusercontent.com/57726348/88478636-a086ee80-cf67-11ea-88c8-3ab6c50c0758.png)

As you can see, the image on the right changes.

I have opted for a simple and clean UI. So I have not added any colors or GIFs.

Looking forward to the next review.

2020-07-27 05:21 UTC, whiz25 approved these changes
## Approved :clap: 
You have done the minimum required for this PR. Please merge and proceed to the next project.

### Martin Afani

2020-07-27 06:00 UTC, merged